# Set color
export CLICOLOR=1
export LSCOLORS=Cxfxcxdxbxegedabagacad

# Highlight matches
export GREP_OPTIONS='--color=auto'

# add other bashrc
. ~/setting/setting.sh

alias count='git ls-files | xargs wc -l'
alias bbs='ssh bbsu@ptt.cc'
alias commitInit='commitizen init cz-conventional-changelog --save --save-exact'
alias makeLog='conventional-changelog -p angular -i CHANGELOG.md -s -r 0'

source ~/setting/bash/prompt.sh

source ~/setting/bash/work.sh ## cdwork
source ~/setting/bash/local.sh ## cdlocal
source ~/setting/bash/server.sh ## run-server
source ~/setting/bash/env.sh ## run-env
source ~/setting/bash/docker.sh ## docker-editor
source ~/setting/bash/setting.sh ## setting
source ~/setting/bash/check.sh ## check
source ~/setting/bash/note.sh ## note

if [ -f ~/setting/bash/custom.sh ]; then
  source ~/setting/bash/custom.sh ## custom command
fi

# other
case $system in
  ($mac)
    # tab autocomplete
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
      . $(brew --prefix)/etc/bash_completion
    fi
    ;;
esac

export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
